import { StyleSheet, Dimensions } from "react-native";
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;
import variables from "./variables";

const styles = StyleSheet.create({
  sub_header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 50,
    width: windowWidth,
    backgroundColor: variables.colors.secondary,
  },
  select_address_box: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: windowWidth - windowWidth / 4,
    height: 50,
    backgroundColor: variables.colors.white,
    borderTopRightRadius: 30,
    borderBottomRightRadius: 30,
    paddingLeft: 10,
  },
  select_address_box_text: {
    color: variables.colors.black,
    marginTop: 2,
    fontSize: 14,
  },
  select_address_box_icon: {
    marginRight: 20,
  },
  estimated_box_time: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 20,
  },
  estimated_box_time_main_text: {
    color: variables.colors.primary,
    fontSize: 11,
    fontWeight: 'bold',
    marginRight: 10,
  },
  estimated_box_time_sub_text: {
    color: variables.colors.primary,
    fontSize: 15,
    fontWeight: 'bold',
    marginRight: 10,
  },
  category_card_container: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    width: windowWidth,
    padding: 15
  },
  category_card: {
    width: windowWidth / 5,
    height: windowWidth / 5.5,
    shadowColor: "#919191",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 5.46,
    elevation: 9,
    borderRadius: 15,
    transform: [{ scale: 1 }],
  },
  category_card_img: {
    flex: 1,
    width: 77,
    borderRadius: 15,
  },
  category_card_text: {
    fontSize: 12,
    marginBottom: 8,
    marginTop: 3,
    color: '#545454',
    textAlign: 'center',
  },
  textHeader: {
    color: variables.colors.white,
    fontSize: 17,
    fontWeight: 'bold',
  },
  middleTabBar: {
    marginTop: -10,
  },
  middleTabBarBtn: {
    width: 54,
    height: 54,
    borderRadius: 27,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: "#4a4a4a",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.52,
    shadowRadius: 5.46,
    borderWidth: 2,
    borderColor: '#d1d1d1',
  },
  campaignCardContainer: {
    display: 'flex',
    backgroundColor: variables.colors.white,
    borderRadius: 15,
    margin: 15,
    marginBottom: 10,
    padding: 10
  },
  campaignCardImg: {
    flex: 1,
    backgroundColor: variables.colors.dark,
    height: 180,
    borderRadius: 15,
    resizeMode: 'contain',
  },
  campaignCardContent: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 12,
    padding: 3
  },
  campaignCardTextTitle: {
    fontSize: 13,
    color: variables.colors.primary,
    fontWeight: 'bold',
  },
  campaignCardText: {
    fontSize: 12,
    paddingTop: 13,
    color: variables.colors.darkgray,
  },
  campaignCardIcon: {
    backgroundColor: variables.colors.white,
    borderRadius: 10,
    padding: 10,
    shadowColor: "#4a4a4a",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.22,
    shadowRadius: 5.46,
    elevation: 9,
  },
  userScreenContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    width: windowWidth,
    marginTop: 20,
  },
  userScreenButton: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 12,
    paddingBottom: 12,
    backgroundColor: variables.colors.white,
    borderWidth: 0.2,
    borderColor: variables.colors.gray,
    shadowColor: "#4a4a4a",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.12,
    shadowRadius: 5.46,
    elevation: 9,
  },
  userScreenButtonText: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    color: variables.colors.dark,
    fontSize: 15.5,
    marginLeft: 10,
  },
  userScreenButtonContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  searchProductContainer: {
    display: 'flex',
    backgroundColor: variables.colors.white,
    height: 50,
  },
  searchProductListText: {
    color: variables.colors.darkgray,
    fontSize: 14,
    marginLeft: 20,
    marginTop: 10,
    marginBottom: 10,
  },
  productListContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: windowWidth,
    height: windowHeight,
    flexWrap: 'wrap',
    backgroundColor: variables.colors.white,
    padding: 10
  },
  productCard: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    backgroundColor: variables.colors.white,
    margin: 10,
    marginBottom: 0,
    height: 160,
  },
  productImgContainer: {
    position: 'relative',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: variables.colors.gray,
    borderRadius: 15,
    padding: 10,
  },
  productCardImg: {
    width: 80,
    height: 80,
    resizeMode: 'cover',
  },
  productImgPlusIcon: {
    position: 'absolute',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: variables.colors.white,
    right: -3,
    top: -7,
    width: 25,
    height: 25,
    shadowColor: "#4a4a4a",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.22,
    shadowRadius: 5.46,
    elevation: 9,
    borderRadius: 5,
    zIndex: 1,
  },
  productCardNameText: {
    textAlign: 'left',
    fontSize: 13,
    marginTop: 2,
  },
  productCardPriceText: {
    textAlign: 'left',
    fontSize: 13,
    color: variables.colors.primary,
    fontWeight: 'bold',
    marginTop: 5,
  },
  productCardPriceTextOld: {
    textAlign: 'left',
    fontSize: 13,
    color: variables.colors.darkgray,
    textDecorationLine: 'line-through',
    textDecorationStyle: 'solid',
    marginTop: 5,
    marginRight: 5,
  },
  productCardPriceContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  productCardSubText: {
    textAlign: 'left',
    fontSize: 12,
    color: variables.colors.darkgray,
  },
  textDialog: {
    textAlign: 'center',
    fontSize: 14,
    color: variables.colors.dark,
    marginTop: 10,
    marginBottom: 10,
  },
  textDialogCancelButton: {
    backgroundColor: variables.colors.darkgray,
    width: 100,
    marginTop: 10,
    marginRight: 10,
  },
  textDialogDoneButton: {
    backgroundColor: variables.colors.primary,
    width: 100,
    marginTop: 10
  },
  flexStart: {
    justifyContent: 'flex-start'
  },
});

export default styles;